### PR TITLE
fix getOS not working with windows

### PR DESCRIPTION
**Pull request by sibouras**

### CODE REVIEW

**Comment by DanielVolchek** [comment]
Oh no! I can't believe I stuck that same section of code back in and broke windows again. That's on me for copying from an old commit. Have you confirmed that sysname works on windows? I read something that gave me the impression that it only worked to compare macos and linux. If it does work I'll merge this in, otherwise checking for dll and then comparing sysname seems like it would work as an alternative approach.

**Comment by sibouras** [comment]
yes im using windows and it works 👍
you can also use `vim.loop.os_uname().version:match("Windows")` which i see more often in plugins

**Comment by DanielVolchek** [comment]
Not sure if you were able to test this correctly, as your commit states if sysname != "windows" return windows

afaik windows doesn't have uname available so I'm gonna stick with using binaryformat for windows and using uname for unix based

**Comment by DanielVolchek** [comment]
Thank you for the pr. If you try now it should work again

**Comment by sibouras** [comment]
works thanks 👍 , and yes if sysname != "windows" always returns true that's why i thought it worked  🤦.
this is the output of running `lua =vim.loop.os_uname()`
```
{
  machine = "x86_64",
  release = "10.0.19044",
  sysname = "Windows_NT",
  version = "Windows 10 Home Single Language"
}
```
`vim.loop.os_uname().version:match("Windows")` this one should work, but the dll version also works so thanks :)

**Pull request closed without merging**
